### ISSUE TITLE
suggestion: support random length

### ISSUE THREAD

**Issue by trondhindenes** [pulumi/pulumi-random#1368]
### Describe what happened

It would be good if it was possible to create secrets of a not-known length. 
so instead of `Length` ot would be possible to do `MinLength` and `MaxLength`, and have the provider choose a length in between those.

### Sample program

N/A

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment]
Hey @trondhindenes, thanks for the suggestion. I believe that should be possible right now but you need two resources:

1. A random int which is a valid length for a secret: https://www.pulumi.com/registry/packages/random/api-docs/randominteger/
2. A random secret which uses the value of the previous int as its length

Something like:

```python
len = random.RandomInteger("len",
    min=10,
    max=20,
)

secret = random.RandomString("secret",
    length=len.result,
    special=True,
    override_special="/@£$")
```

LMK if you have any other questions.

**Comment by trondhindenes** [comment]
Nice, didnt think of that! I will test this out. Thanks!
