### ISSUE TITLE
Random certs

### ISSUE THREAD

**Issue by headconnect** [pulumi/pulumi-random#162]
It would just be really cool if Random could generate certificates.
## Affected feature
Some helm charts cause regeneration of certificates every time they are run, it would be good to feed them with certificates generated with random so that they can be tracked in state and not regenerated every `up`

**Comment by stack72** [comment]
Hi @headconnect 

Not sure if you've seen Pulumi-tls package - that can generate random self signed certificates for you

Paul

**Comment by headconnect** [comment]
Of course I hadn't! Thanks for the heads, up, this is brilliant.

**Comment by stack72** [comment]
I'm going to close this out :) if there are any other issues here then let me know
