### ISSUE TITLE
RandomPassword missing documentation

### ISSUE THREAD

**Issue by lily-es** [pulumi/pulumi-random#220]
RandomPassword is missing a description in the documentation. Also, the documentation should probably explicitly note that the passwords generated by this resource are treated as a secret by default and obfuscated as well as stored as encrypted in the state.

https://www.pulumi.com/registry/packages/random/api-docs/randompassword/

**Comment by aviflat** [comment]
Looks like this has been fixed? Looking at that page now, there’s this sentence near the top:

> Identical to random.RandomString with the exception that the result is treated as sensitive and, thus, _not_ displayed in console output.

**Comment by lily-es** [comment]
Yep, looks like it has! Thanks for the heads up
