### ISSUE TITLE
The v4.8.1 release removes the BcryptHash output

### ISSUE THREAD

**Issue by bison** [pulumi/pulumi-random#236]
### What happened?

The [v4.8.1](https://github.com/pulumi/pulumi-random/releases/tag/v4.8.1) release upgraded the Random Terraform Provider to v3.3.2 and dropped the `BcryptHash` output from the resource. I think this was probably unintentional, as the output still exists in Terraform.

I'm guessing this probably has something to do with this recent refactor in the Terraform provider: https://github.com/hashicorp/terraform-provider-random/pull/254 -- but that's just a guess.

### Steps to reproduce

- Create a `RandomPassword` resource with version v4.8.0, and use the `BcryptHash` output.
- Update to v4.8.1, and the same code no longer builds.

### Expected Behavior

The `BcryptHash` output still exists.

### Actual Behavior

The `BcryptHash` output was removed on a minor version update.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @bison 

I am sorry this has happened - I will get this looked into asap!

Paul

**Comment by AaronFriel** [comment]
Hey @bison, as we're now tracking the latest upstream release, it looks like the `bcrypt_hash` output should be present, I've checked our SDKs and see the [output](https://github.com/pulumi/pulumi-random/blob/master/sdk/go/random/randomPassword.go#L112-L116) on all RandomPassword instances.

Regarding the minor version update, we follow upstream's decision when making breaking changes. We're currently evaluating whether that's the best thing for our users, with no decision at this time.

I'm closing this for now, but if you see any issues with using this output, please create a new issue!
