### ISSUE TITLE
Pulumi stack got stuck with random 4.9.0 version

### ISSUE THREAD

**Issue by lgbrotas** [pulumi/pulumi-random#265]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
Some weeks ago we deployed a stack and the version of the lib was 4.9.0, now we are trying to deploy it again but fail to download version 4.9.0.

**One message that we found was this one:**
plugin random 4.9.0 is required by first-class provider URN

**And the error that we faced is this one:**
defaultSink::Error(error: could not load plugin for random provider 'URN': Could not automatically download and install resource plugin 'pulumi-resource-random' at version v4.9.0, install the plugin using `pulumi plugin install resource random v4.9.0`.
Underlying error: error downloading plugin random to file: failed to download plugin: random-4.9.0: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-random-v4.9.0-linux-amd64.tar.gz)
error: could not load plugin for random provider URN': Could not automatically download and install resource plugin 'pulumi-resource-random' at version v4.9.0, install the plugin using `pulumi plugin install resource random v4.9.0`.
Underlying error: error downloading plugin random to file: failed to download plugin: random-4.9.0: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-random-v4.9.0-linux-amd64.tar.gz

What could I do to solve this?

Thanks, Lucas

**Comment by t0yv0** [comment]
Thanks for reporting the issue @lgbrotas 

We discovered a critical issue with the 4.9.0 release and deprecated it to limit blast radius of the bug, but we owe users like you some instructions how to recover your stack state gracefully from the state it got into by using 4.9.0.

A similar issue was reported for the TLS provider: https://github.com/pulumi/pulumi-tls/issues/169

Piotr mentions having to manually edit the stack state to recover. I'm going to have a look at trying to script this process.

**Comment by t0yv0** [comment]
Worth a try!

**Comment by lgbrotas** [comment]
We have changed the inputs and outputs and worked.

Should I close this issue?

**Comment by t0yv0** [comment]
Thank you for reprint back @lgbrotas ! I will close for now then if you are unblocked. But if anyone else experiences the issue again please feel free to reopen and we can look back at scripted workarounds.
