### ISSUE TITLE
random.RandomPassword API docs are broken

### ISSUE THREAD

**Issue by cnunciato** [pulumi/pulumi-random#286]
Something seems to have gone awry with the rendering:

https://www.pulumi.com/registry/packages/random/api-docs/randompassword/

![image](https://user-images.githubusercontent.com/274700/221372982-47818000-026e-4b97-b71f-343397ffc0a1.png)

**Comment by susanev** [comment]
@cnunciato i know it may seem silly on these, but i still think its helpful to describe in text what you are trying to highlight with a screenshot, or else add some indication to the screenshot.

**Comment by cnunciato** [comment]
Oh, sorry about that — I thought that’d be clear from the screenshot. Its the center section of the page, so pretty much everything in the center column below the heading.

**Comment by jazzyfresh** [comment]
Thank you for the clarification! 

It appears that the section `Avoiding Replacement` is rendered incorrectly:
* The first CLI block includes documentation text appended to the CLI command
  * <img width="874" alt="Screen Shot 2023-03-10 at 5 17 41 PM" src="https://user-images.githubusercontent.com/1182129/224456820-d274b57e-966b-4e4d-b717-4d0cdacd5eff.png">
* The rest of that documentation sentence and some code appears below the CLI box in plain text
* There should be a list with three items and code blocks for each item
  * <img width="839" alt="Screen Shot 2023-03-10 at 5 22 34 PM" src="https://user-images.githubusercontent.com/1182129/224457101-fbdb0741-3986-4144-bb01-680208176dfa.png">
