### ISSUE TITLE
Unable to generate passwords > 72 bytes

### ISSUE THREAD

**Issue by KaoruDev** [pulumi/pulumi-random#393]
### What happened?

```
    error: Hash Generation Error: While attempting to generate a hash from the password an error occurred.

    Verify that the state contains a populated 'result' field, using 'terraform state show', and retry the operation

    Original Error: bcrypt: password length exceeds 72 bytes
```

### Expected Behavior

Be able to generate a random password with length > 72.

### Steps to reproduce

```ts
new random.RandomPassword(
  "me-secret",
  { length: 256 },
  { parent: this }
).result
```

**Note**
The above works on `v4.11.1`

### Output of `pulumi about`

```
CLI
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       darwin
Version  12.6.7
Arch     x86_64
```

### Additional context

Seems related to: https://github.com/hashicorp/terraform-provider-random/pull/397

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @KaoruDev. Thanks for letting us know about this issue. I have reproduced locally with this program:

```ts
import * as random from "@pulumi/random";

new random.RandomPassword(
  "me-secret",
  { length: 256 },
)
```
