### ISSUE TITLE
New python release breaks provider installation

### ISSUE THREAD

**Issue by glennpratt** [pulumi/pulumi-random#417]
### What happened?

Suddenly github-actions started failing for us today with 403 errors.

It seems the issue is a new python release of 4.13.4 which doesn't exist in the provider proper. Excluding this python version avoids the issue.

### Example

I don't have a public example.

```
 Diagnostics:
    pulumi:providers:random (default_4_13_4):
      error: Could not automatically download and install resource plugin 'pulumi-resource-random' at version v4.13.4, install the plugin using `pulumi plugin install resource random v4.13.4`: error downloading provider random to file: failed to download plugin: random-4.13.4: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-random-v4.13.4-linux-amd64.tar.gz
```

### Output of `pulumi about`

```
CLI          
Version      3.77.1
Go Version   go1.20.6
Go Compiler  gc

Plugins
NAME        VERSION
command     0.8.1
kubernetes  3.21.4
linode      3.12.0
python      unknown
random      4.13.2
tls         4.10.0

Host     
OS       darwin
Version  13.5.2
Arch     arm64

This project is written in python: executable='/Users/REDACTED/default/bin/python3' version='3.11.4
'

Current Stack: organization/app-platform/dev

TYPE                                                  URN
REDACTED


Found no pending operations associated with dev

Backend        
Name           REDACTED
URL            file://~
User           REDACTED
Organizations  

Dependencies:
NAME               VERSION
ansible            7.5.0
black              23.3.0
kubernetes         27.2.0
pip                23.0.1
polling2           0.5.0
pulumi-command     0.8.1
pulumi-kubernetes  3.21.4
pulumi-linode      3.12.0
pulumi-random      4.13.2
pulumi-tls         4.10.0
setuptools         65.5.0
wheel              0.41.1

Pulumi locates its logs in /var/folders/9q/b_ncxg310xb5h1xcd0s87_k80000gq/T/ by default

```

### Additional context

# Workaround

requirements.txt
```
pulumi-random>=4.12.0,!=4.13.4
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Are you still experiencing the issue? I cannot reproduce at the moment. Note that https://github.com/pulumi/pulumi-random/actions/runs/6201702245 just recently finished and unfortunately we had to do a few restarts on that, which might have temporarily exposed the customers to a broken state. If that's so we'll follow up internally how to ensure the pipelines are observably atomic. But first I'd like to make sure you're no longer affected.

**Comment by glennpratt** [comment]
Thanks @t0yv0, that's almost certainly it. I'm waiting on a build queue on my end to clear to verify.

And thank for thinking about the process. If not atomic, at lease language providers only after the provider itself might be good enough.

**Comment by t0yv0** [comment]
I think usually provider publishes first, and SDKs later, but given the non-golden-path retry scenario something must have gone amock.

**Comment by glennpratt** [comment]
Ok, yes, verified on my end. Feel free to close this ticket whenever you see fit.

**Comment by t0yv0** [comment]
Thank you!
