### ISSUE TITLE
Can't install some versions and other versions are missing dependencies.

### ISSUE THREAD

**Issue by jeffclay** [pulumi/pulumi-random#725]
### What happened?

Python version of provider is broken.

### Example

**version 4.15.1 and prior versions**
 - `sdk/python/pulumi_random/_utilities.py` tries to import `pkg_resources`.
 - `pkg_resources` not listed as a dependency in `sdk/python/pyproject.toml`

**version 4.16.0a1709077192**
This is the latest showing in pypi. This version and several preceding it produce the following error:

> Diagnostics:
  pulumi:providers:random (default_4_16_0_alpha_1709077192):
    error: Could not automatically download and install resource plugin 'pulumi-resource-random' at version v4.16.0-alpha.1709077192, install the plugin using `pulumi plugin install resource random v4.16.0-alpha.1709077192`: error downloading provider random to file: failed to download plugin: random-4.16.0-alpha.1709077192: 403 HTTP error fetching plugin from https://get.pulumi.com/releases/plugins/pulumi-resource-random-v4.16.0-alpha.1709077192-linux-amd64.tar.gz

### Output of `pulumi about`

pulumi about
CLI          
Version      3.106.0
Go Version   go1.22.0
Go Compiler  gc

Plugins
NAME    VERSION
gcp     7.11.0
gitlab  6.9.0
python  unknown
random  4.16.0-alpha.1709077192

Host     
OS       fedora
Version  39
Arch     x86_64

This project is written in python: executable='/home/.../my_project/.venv/bin/python3' version='3.12.2'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com
User           Unknown
Organizations  
Token type     personal

Dependencies:
NAME           VERSION
pip            23.2.1
pulumi_gcp     7.11.0
pulumi_gitlab  6.9.0
pulumi_random  4.16.0a1709077192

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @jeffclay. I'm sorry to hear that v4.15.1 is broken on python. I'm going to do a patch release now, which should fix the problem.

**Comment by iwahbe** [comment]
v4.16.0 is released, and it should be installable for python. It is on my machine. If it's still not working for you, please let me know.
