### ISSUE TITLE
[bug] randomPet missing id output

### ISSUE THREAD

**Issue by brandonkal** [pulumi/pulumi-random#77]

**Comment by leezen** [comment]
Could you please provide more details? I wasn't able to repro with this simple program:

```typescript
import * as pulumi from "@pulumi/pulumi";
import { RandomPet } from "@pulumi/random";

const pet = new RandomPet("my-pet");

exports.petId = pet.id;
```

**Comment by brandonkal** [comment]
I believe the issue was that it does not exist in the TypeScript types. If that is not it, feel free to close this one.

**Comment by leezen** [comment]
Thanks for the update. I see the TS definitions, so I don't think that's it either. Closing for now -- please reopen if you do run into a problem with this.
